export const PESSOA_FISICA = 'PESSOA_FISICA';

export const updatePessoaFisica = (data) => ({
  type: PESSOA_FISICA,
  payload: {
    pfPj: [
      {
        clienteVM: data.clienteVM || null,
        idCliente: data.idCliente || null,
        pessoaJuridicaVM: {
          id: data.idPessoaJuridica || null,
          cnpj: data.cnpj || null,
          nomeFantasia: data.nomeFantasia || null,
          dataCriacao: data.dataCriacao || null,
          dataCriacaoString: data.dataCriacaoString || null,
          dataCriacaoRelatorio: data.dataCriacaoRelatorio || null,
          razaoSocial: data.razaoSocial || null,
          telefone: data.telefone || null,
          email: data.email || null,
          cep: data.cep || null,
          endereco: data.endereco || null,
          porte: data.porte || null,
          descPorte: data.descPorte || null,
          atividade: data.atividade || null,
          descricaoStatusReceita: data.descricaoStatusReceita || null,
          descricaoStatusSebrae: data.descricaoStatusSebrae || null,
          preenchidoManualmente: data.preenchidoManualmente || null,
          cnaeId: data.cnaeId || null,
          cnaeDesc: data.cnaeDesc || null,
          codNaturezaJuridicaSas: data.codNaturezaJuridicaSas || null,
          descNaturezaJuridica: data.descNaturezaJuridica || null,
          codNaturezaJuridicaConcla: data.codNaturezaJuridicaConcla || null,
          quantidadeFuncionarios: data.quantidadeFuncionarios || null,
          statusSincronismoSas: data.statusSincronismoSas || null,
          codConstTipoEmpreendimento: data.codConstTipoEmpreendimento || null,
          codParceiroSas: data.codParceiroSas || null,
        },
        idPessoaJuridica: data.idPessoaJuridica || null,
      },
    ],
    atendimentos: data.atendimentos || null,
    pessoaJuridicaLista: data.pessoaJuridicaLista || null,
    clienteEnderecos: [
      {
        id: data.idEndereco || null,
        idCliente: data.idCliente || null,
        numSeqEnd: data.numSeqEnd || null,
        endCorresp: data.endCorresp || null,
        codLogr: data.codLogr || null,
        descEndereco: data.descEndereco || null,
        numero: data.numero || null,
        complemento: data.complemento || null,
        codBairro: data.codBairro || null,
        descBairro: data.descBairro || null,
        codCid: data.codCid || null,
        descCid: data.descCid || null,
        codEst: data.codEst || null,
        descEst: data.descEst || null,
        codPais: data.codPais || null,
        descPais: data.descPais || null,
        cep: data.cep || null,
        endInternacional: data.endInternacional || null,
        indCorrespond: data.indCorrespond || null,
        principal: data.principal || null,
        codigoMunicipioRM: data.codigoMunicipioRM || null,
        tpOperacao: data.tpOperacao || null,
        autorizaCorrespondencia: data.autorizaCorrespondencia || null,
        isEmptyCep: data.isEmptyCep || false,
        isEmptyDescEndereco: data.isEmptyDescEndereco || false,
        isEmptyDescBairro: data.isEmptyDescBairro || false,
        isEmptyMunicipio: data.isEmptyMunicipio || false,
        // ... outros campos ...
      },
    ],
    clienteContatos: [
      {
        id: data.idContato1 || null,
        cpf: data.cpf || null,
        numSeqCom: data.numSeqCom1 || null,
        codComunic: data.codComunic1 || null,
        descComunic: data.descComunic1 || null,
        numero: data.numero1 || null,
        indInternet: data.indInternet1 || null,
        recebeContato: data.recebeContato1 || null,
        recebeSMS: data.recebeSMS1 || null,
        principal: data.principal1 || null,
        inputVazio: data.inputVazio1 || false,
        tpContato: data.tpContato1 || null,
        tpOperacao: data.tpOperacao1 || null,
        autorizaLigacao: data.autorizaLigacao1 || null,
        autorizaMensagem: data.autorizaMensagem1 || null,
        // ... outros campos ...
      },
      {
        id: data.idContato2 || null,
        cpf: data.cpf || null,
        numSeqCom: data.numSeqCom2 || null,
        codComunic: data.codComunic2 || null,
        descComunic: data.descComunic2 || null,
        numero: data.numero2 || null,
        indInternet: data.indInternet2 || null,
        recebeContato: data.recebeContato2 || null,
        recebeSMS: data.recebeSMS2 || null,
        principal: data.principal2 || null,
        inputVazio: data.inputVazio2 || false,
        tpContato: data.tpContato2 || null,
        tpOperacao: data.tpOperacao2 || null,
        autorizaLigacao: data.autorizaLigacao2 || null,
        autorizaMensagem: data.autorizaMensagem2 || null,
        // ... outros campos ...
      },
      {
        id: data.idContato3 || null,
        cpf: data.cpf || null,
        numSeqCom: data.numSeqCom3 || null,
        codComunic: data.codComunic3 || null,
        descComunic: data.descComunic3 || null,
        numero: data.numero3 || null,
        indInternet: data.indInternet3 || null,
        recebeContato: data.recebeContato3 || null,
        recebeSMS: data.recebeSMS3 || null,
        principal: data.principal3 || null,
        inputVazio: data.inputVazio3 || false,
        tpContato: data.tpContato3 || null,
        tpOperacao: data.tpOperacao3 || null,
        autorizaLigacao: data.autorizaLigacao3 || null,
        autorizaMensagem: data.autorizaMensagem3 || null,
      },
    ],
    workflows: data.workflows || null,
    id: data.id || null,
    cpf: data.pfCpf || null,
    nome: data.pfNome || null,
    dataNascimneto: data.pfDataNascimento || null,
    dataNascimnetoFormatada: data.pfDataNascimentoFormatada || null,
    email: data.email || null,
    telefone: data.telefone || null,
    cep: data.cep || null,
    endereco: data.endereco || null,
    tituloEleitor: data.tituloEleitor || null,
    rg: data.rg || null,
    sexo: data.sexo || null,
    escolaridade: data.escolaridade || null,
    statusReceita: data.statusReceita || null,
    statusSebrae: data.statusSebrae || null,
    possuiDeficiencia: data.possuiDeficiencia || null,
    lgpd: data.lgpd || null,
    codUfLgpd: data.codUfLgpd || null,
    descUfLgpd: data.descUfLgpd || null,
    codParcLgpd: data.codParcLgpd || null,
    dtAceiteLgpd: data.dtAceiteLgpd || null,
    nomeParceiroLgpd: data.nomeParceiroLgpd || null,
    tipoPessoaFisica: data.tipoPessoaFisica || null,
    verificado: data.verificado || null,
    qtdTentativas: data.qtdTentativas || 0,
    estudante: data.estudante || false,
    produtorRural: data.produtorRural || false,
    dataNascimnetoString: data.pfDataNascimentoString || null,
    dataNascimnetoRelatorio: data.pfDataNascimentoRelatorio || null,
    codcfo: data.codcfo || null,
  },
});
