export const PESSOA_JURIDICA = 'PESSOA_JURIDICA';
export const updatePessoaJuridica = (data: {
  clienteVM: null,
  idCliente: Number,
  idPessoaJuridica: Number,
  pessoaJuridicaVM: {
    id: Number,
    cnpj: Number,
    nomeFantasia: String,
    dataCriacao: string,
    dataCriacaoString: string,
    dataCriacaoRelatorio: string,
    razaoSocial: string,
    cep: number,
    endereco: string,
    porte: number,
    descPorte: string,
    atividade: string,
    descricaoStatusReceita: string,
    descricaoStatusSebrae: string,
    preenchidoManualmente: number,
    cnaeId: number,
    cnaeDesc: string,
    descNaturezaJuridica: string,
    codNaturezaJuridicaConcla: number,
    quantidadeFuncionarios: number,
    email: null,
    codNaturezaJuridicaSas: null,
    telefone: null,
    statusSincronismoSas: null,
    codConstTipoEmpreendimento: null,
    codParceiroSas: null
  },
}) => ({
  type: PESSOA_JURIDICA,
  payload: data,
});
