export const ATENDIMENTO = 'ATENDIMENTO';
export const updateAtendimento = (data: {
  workflows: null,
  id: null,
  tituloEleitor: null,
  rg: null,
  sexo: null,
  escolaridade: null,
  statusReceita: null,
  statusSebrae: null,
  possuiDeficiencia: null,
  lgpd: null,
  codUfLgpd: null,
  descUfLgpd: null,
  codParcLgpd: null,
  nomeParceiroLgpd: null,
  tipoPessoaFisica: null,
  verificado: null,
  qtdTentativas: number,
  dataNascimnetoString: string,
  dataNascimnetoRelatorio: string,
  codcfo: null,
  atendimentos: null,
}) => ({
  type: ATENDIMENTO,
  payload: data,
});
