// _app.tsx
import React from 'react';
import { AppProps } from 'next/app';
import { register, unregister } from 'next-offline/runtime';
import { Metadata } from 'next';

export const metadata: Metadata = {
  manifest: '/manifest.json',
  title: "Create Next App",
  description: "Generated by create next app",
};

function MyApp({ Component, pageProps }: AppProps) {
  React.useEffect(() => {
    const isProduction = process.env.NODE_ENV === 'production';

    if (isProduction) {
      register();
    } else {
      unregister();
    }
  }, []);

  return <Component {...pageProps} />;
}

export default MyApp;
