// pages/_app.tsx
import React from 'react';
import { AppProps } from 'next/app';
import { register, unregister } from 'next-offline/runtime';
import { Metadata } from 'next';

// Importe a instância do Prisma Client
import prisma from '../lib/prisma';

export const metadata: Metadata = {
  manifest: '/manifest.json',
  title: "Create Next App",
  description: "Generated by create next app",
};

function MyApp({ Component, pageProps }: AppProps) {
  React.useEffect(() => {
    const isProduction = false;

    if (isProduction) {
      register();
    } else {
      unregister();
    }
  }, []);

  // Use a instância do Prisma Client
  return <Component {...pageProps} />;
}

export default MyApp;
